services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./django/app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - app_network

  django:
    build:
      context: ./django
    volumes:
      - ./django/app:/app
    # ports:
    #   - 8000:8000
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    # ports:
    #   - 3306:3306
    volumes:
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
