services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./fastapi/app:/var/www/html/api
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app_network

  fastapi:
    build:
      context: ./fastapi
    volumes:
      - ./fastapi/app:/app  # Volume para os arquivos da aplicação FastAPI
    networks:
      - app_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: